
const partGroups = {
  nose :[
    "Nose Depth",
    "Nose Pinch",
    "Nose Scale",
    "Nose Height",
    "Nose Tip Depth",
    "Nose Tip Point",
    "Nose Tip Round",
    "Nose Tip Height"
  ],
  head: [
      "Caleus",
      "Denisa",
      "Dimitri",
      "Flora",
      "Magda",
      "Matt",
      "Michelle",
      "Ruben",
      "Samantha",
      "Timothy",
      "Aanya",
      "Ayako",
      "Cristy",
      "Debbie",
      "Gabriel",
      "Gloria",
      "Jamal",
      "Lori",
      "Mei",
      "Travis",
      "CC3+_Neutral Female",
      "CC3+_Katherine_Head",
      "CC3+_Jody_Head",
      "CC3_Base Female",
      "CC1_Base Female",
      "CC3+_Neutral Male",
      "CC3+_Caleb_Head",
      "CC3+_Kevin_Head",
      "CC3_Base Male",
      "CC1_Base Male",
      "Head HA Female Asian",
  ],
  body: [
    "CC3+_Neutral Female",
    "CC3+_Katherine_Body",
    "CC3+_Jody_Body",
    "CC3_Base Female",
    "CC1_Base Female",
    "CC3_Base Female A",
    "CC3+_Neutral Male",
    "CC3+_Caleb_Body",
    "CC3+_Kevin_Body",
    "CC3_Base Male",
    "CC1_Base Male",
    "CC3_Base Male A",
    "Body HA Female Asian",
    "Body HA Male Herculean",
    "Body HA Female Herculean",
    "Body HA Female Athletic",
    "Body HA Male Athletic"
  ]
}

module.exports = { partGroups }
